-- SQL para configurar a tabela de leads no Supabase
-- Execute este script no SQL Editor do Supabase (https://rtodbbiugsrhupmyarut.supabase.co)

-- Criar tabela de leads se não existir
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);

-- Habilitar Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir INSERT com anon key
-- Isso permite que o totem insira leads usando a chave anônima
CREATE POLICY "Permitir INSERT de leads para usuários anônimos"
ON leads
FOR INSERT
TO anon
WITH CHECK (true);

-- Criar política para permitir SELECT (opcional, para admin)
-- Descomente se quiser permitir leitura com anon key
-- CREATE POLICY "Permitir SELECT de leads"
-- ON leads
-- FOR SELECT
-- TO authenticated, anon
-- USING (true);

-- Verificar se a tabela foi criada corretamente
SELECT 
  table_name,
  column_name,
  data_type,
  is_nullable
FROM information_schema.columns
WHERE table_name = 'leads'
ORDER BY ordinal_position;

