-- =========================================
-- SETUP MULTI-TENANT PARA SUPABASE
-- =========================================
-- Execute este script completo no SQL Editor do Supabase
-- URL: https://rtodbbiugsrhupmyarut.supabase.co

-- =========================================
-- PASSO 1: CRIAR TABELA DE TENANTS (CLIENTES)
-- =========================================
-- Esta tabela armazenará informações sobre cada cliente/totem

CREATE TABLE IF NOT EXISTS tenants (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar índice para buscas rápidas por slug
CREATE INDEX IF NOT EXISTS idx_tenants_slug ON tenants(slug);

-- Comentários para documentação
COMMENT ON TABLE tenants IS 'Tabela que armazena os clientes (tenants) da plataforma';
COMMENT ON COLUMN tenants.slug IS 'Identificador único URL-friendly usado pelos totems';

-- =========================================
-- PASSO 2: ATUALIZAR TABELA DE LEADS
-- =========================================
-- Adicionar coluna tenant_id para vincular cada lead ao seu cliente

-- Se a tabela leads não existir, criar do zero
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Adicionar coluna tenant_id (se ainda não existir)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='leads' AND column_name='tenant_id'
    ) THEN
        ALTER TABLE leads ADD COLUMN tenant_id UUID REFERENCES tenants(id);
    END IF;
END $$;

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_leads_tenant_id ON leads(tenant_id);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);

-- =========================================
-- PASSO 3: CONFIGURAR ROW LEVEL SECURITY (RLS)
-- =========================================

-- Habilitar RLS nas tabelas
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- =========================================
-- POLÍTICAS PARA TENANTS
-- =========================================

-- Permitir leitura de tenants para usuários autenticados
DROP POLICY IF EXISTS "Permitir SELECT de tenants para service role" ON tenants;
CREATE POLICY "Permitir SELECT de tenants para service role"
ON tenants
FOR SELECT
TO authenticated, service_role
USING (true);

-- Permitir INSERT de tenants apenas para service_role
DROP POLICY IF EXISTS "Permitir INSERT de tenants para service role" ON tenants;
CREATE POLICY "Permitir INSERT de tenants para service role"
ON tenants
FOR INSERT
TO service_role
WITH CHECK (true);

-- =========================================
-- POLÍTICAS PARA LEADS
-- =========================================

-- Permitir INSERT de leads para usuários anônimos (totems)
-- Cada totem pode inserir leads para qualquer tenant
DROP POLICY IF EXISTS "Permitir INSERT de leads para totems" ON leads;
CREATE POLICY "Permitir INSERT de leads para totems"
ON leads
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Permitir SELECT de leads apenas para usuários autenticados
-- (Futuramente, podemos restringir para que cada tenant veja apenas seus leads)
DROP POLICY IF EXISTS "Permitir SELECT de leads" ON leads;
CREATE POLICY "Permitir SELECT de leads"
ON leads
FOR SELECT
TO authenticated, service_role
USING (true);

-- =========================================
-- PASSO 4: INSERIR TENANTS DE EXEMPLO
-- =========================================

-- Inserir alguns tenants para teste
INSERT INTO tenants (name, slug) VALUES
  ('Loja de Roupas A', 'loja-roupas-a'),
  ('Evento Tech 2025', 'evento-tech-2025'),
  ('Concessionária Y', 'concessionaria-y'),
  ('Loja Exemplo 001', 'loja-exemplo-001')
ON CONFLICT (slug) DO NOTHING;

-- =========================================
-- PASSO 5: VERIFICAR INSTALAÇÃO
-- =========================================

-- Ver todos os tenants criados
SELECT 
  id,
  name,
  slug,
  created_at
FROM tenants
ORDER BY created_at DESC;

-- Ver estrutura da tabela leads
SELECT 
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'leads'
ORDER BY ordinal_position;

-- =========================================
-- INFORMAÇÕES IMPORTANTES
-- =========================================

-- 1. Guarde os IDs dos tenants - você precisará deles!
-- 2. Cada lead DEVE ter um tenant_id válido
-- 3. Use a chave service_role para criar tenants
-- 4. Use a chave anon para inserir leads (pelos totems)

-- Verificar se há leads sem tenant_id (se houver leads antigos)
SELECT COUNT(*) as leads_sem_tenant
FROM leads
WHERE tenant_id IS NULL;

-- =========================================
-- FIM DO SETUP
-- =========================================

-- 🎉 Se chegou até aqui sem erros, seu banco multi-tenant está pronto!

